### ISSUE TITLE
Can this break the connection between two linked Bluetooth devices?

### ISSUE THREAD

**Issue by itewqq** [lws803/BLE-jammer#1]
Can this break the connection between two linked Bluetooth devices? 
Or do you have any ideas about this? Thank you very much.

**Comment by lws803** [comment]
Hi itewqq,

Hmm it wouldn't work against traditional Bluetooth. But it could BLE devices from communicating further since they will not be able to discover each other on subsequent iterations.

**Comment by itewqq** [comment]
@lws803 Oh sorry to have you misunderstood, but what I'm considering is when there are two already connected BLE devices, how to make them disconnect with radio Interference?

**Comment by lws803** [comment]
Oh I don't think that is possible unless you have a jammer which can cover a wider bandwidth (all 40 channels). It is definitely achievable but you'll need to do a bit of signal processing (multiply a sine wave and dirac comb for example) and then broadcast that with a radio circuit.

**Comment by itewqq** [comment]
I see... Thanks for the reply!
