### ISSUE TITLE
How to select the channels? 

### ISSUE THREAD

**Issue by Petros626** [lws803/BLE-jammer#2]
Hey,

At the beginning of the code you list Radio, radio, radio3 with PA0 etc.

Where you can set the three frequencies?

**Comment by lws803** [comment]
Hey @Petros626 ! Thanks for checking out this repo, frequencies for the 3 radios are set at the following lines:

- radio: https://github.com/lws803/BLE-jammer/blob/7fea999dd1d69c1c2e6774b06a0416380e9f7e2e/nrf_jammer/nrf_jammer.ino#L33
- radio 2: https://github.com/lws803/BLE-jammer/blob/7fea999dd1d69c1c2e6774b06a0416380e9f7e2e/nrf_jammer/nrf_jammer.ino#L41
- radio 3: https://github.com/lws803/BLE-jammer/blob/7fea999dd1d69c1c2e6774b06a0416380e9f7e2e/nrf_jammer/nrf_jammer.ino#L49

They're called channels here in BLE, but you can see the exact frequencies for each channel here https://www.rfwireless-world.com/Terminology/BLE-Advertising-channels-and-Data-channels-list.html

**Comment by Petros626** [comment]
Oh God haha so obvious didn't see it all the time 😂
Thank you for the hint.
