### ISSUE TITLE
Channel selection in your code

### ISSUE THREAD

**Issue by Petros626** [lws803/BLE-jammer#3]
Hey,

another interesting question is about the choosen channel numbers:
```
80 - not available in the source (https://www.rfwireless-world.com/Terminology/BLE-Advertising-channels-and-Data-channels-list.html)
26 - 2458 MHz
2 - 2408 MHz
```
For my understanding it's necessary to block the three advertising channels and not specific data channels. The picture in the repo shows the frequencies: **2402 MHz**, **2426 MHz** and **2480 MHz**

So I don't understand the selection should it not be:

```
37 - 2402 MHz
38 - 2426 MHz
39 - 2480 MHz
```

**Comment by lws803** [comment]
Ohh 🤦 my bad, I forgot to mention that the nrf module accepts a number from `0...124` for setting channels. And the number here corresponds to the following channel, based on the formula (https://nrf24.github.io/RF24/classRF24.html#a5e6e5a5f6c85d2638381cab2c0f3702e):

```
2400 MHz + <channel number>
```

So in this case we have

```
37 -> 2402 MHz -> 2400 + <2>
38 -> 2426 MHz -> 2400 + <26>
39 -> 2480 -> 2400 + <80>
```

**Comment by Petros626** [comment]
Okay good 👍🏼

Maybe you should add it in the description of the repo or as a comment in the code.
