### ISSUE TITLE
Could this work with 1 antenna only?

### ISSUE THREAD

**Issue by voidegg** [lws803/BLE-jammer#4]

**Comment by lws803** [comment]
Hey @voidegg thanks for checking out the repo, unfortunately it would not work with 1 antenna only. The time it takes to switch to the next frequency / channel will be too long and render jamming ineffective.

Unfortunately, I do not have the math to prove this but I did the math before based on the switching delay obtained from NRF's spec sheet 😅

**Comment by voidegg** [comment]
huh, i tried searching for the switching delay to check myself but got frustrated and decided to ask it here instead. thanks for the response
